#!/bin/bash

# Create storage for disk images, ensuring the correct permissions as that
# will dictate the owner/group the images are created as, and whether or
# not qemu can actually access them
mkdir -p /var/lib/staging-hypervisor-agent
chown libvirt-qemu:kvm /var/lib/staging-hypervisor-agent
